### PR TITLE
fix: footer

### PR DESCRIPTION
**Pull request by shujaurrahman**
The footer position fixed is hiding the index content.
context [issue: #6]
@SuhelKhanCA @exc33ded  
image

Removing Position: fixed solves 
image

### CODE REVIEW

**Comment by SuhelKhanCA** [comment]
Dear Shuja,
This PR is causing issues to other pages:
### Login
image

### Resgister
image


And thanks for letting me know. I have corrected this bug in other way.

**Comment by shujaurrahman** [comment]
cool @SuhelKhanCA 
I would like to improve the frontend of this projects.
is that good to go.

**Comment by SuhelKhanCA** [comment]
Yeah @shujaurrahman 
Why not brother. Make improvement in the frontend and let me know. I also realized that jinja2 templating is not very well applied here, and I think we all have made this project to this level. I hope, in future, we will bring more functionality in the project.

**Comment by exc33ded** [comment]
Good work Guys!!

**Pull request merged**
